### Get all images
GET http://localhost:3000/api/images

### Get one image by ID (API 1) - GOOD
GET http://localhost:3000/api/images/69b1bf6193fcdd6286fc224f

### Rename image (API 2) - GOOD (204 expected)
PATCH http://localhost:3000/api/images/69b1bf6193fcdd6286fc224f
Content-Type: application/json

{
  "name": "NOt a cat"
}

### Rename image - BAD REQUEST (400) missing "name"
PATCH http://localhost:3000/api/images/69b1bf6193fcdd6286fc224f
Content-Type: application/json

{
  "notName": "Name missing"
}

### Rename image - NOT FOUND (404) invalid ObjectId format
PATCH http://localhost:3000/api/images/TabbyCat
Content-Type: application/json

{
  "name": "Not found"
}

### Rename image - CONTENT TOO LARGE (413) name > 100 chars
PATCH http://localhost:3000/api/images/69b1bf6193fcdd6286fc224f
Content-Type: application/json

{
  "name": "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
}